export const UsersList = [
    {"_id":1,
        "firstName": "Iratni",
        "lastName":"Sara",
        "email":"ms_iratni@esi.dz",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":2,
        "firstName": "Iratni",
        "lastName":"Malak",
        "email":"malouka@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":3,
        "firstName": "Iratni",
        "lastName":"Asma",
        "email":"isoumyu235@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },{"_id":4,
        "firstName": "Iratni",
        "lastName":"Yassmin",
        "email":"dsfuurt20_@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":5,
        "firstName": "Iratni",
        "lastName":"Selma",
        "email":"bselsatre@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":6,
        "firstName": "Iratni",
        "lastName":"Amira",
        "email":"mr_amira@esi.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":7,
        "firstName": "Iratni",
        "lastName":"Amina",
        "email":"ma_medabis@esi.dz",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":8,
        "firstName": "Bensemane",
        "lastName":"Mohamed Reda",
        "email":"dsfuurt20_@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":9,
        "firstName": "Mshiris",
        "lastName":"Oussama",
        "email":"ouss_yau45@gmail.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":10,
        "firstName": "Bouhali",
        "lastName":"Rabiaa",
        "email":"mr_amira@esi.com",
        "role":"user",
        "DirPath":"/Downloads/public"
    },
    {"_id":11,
        "firstName": "Bokhari",
        "lastName":"Abdeljalil",
        "email":"ma_medabis@esi.dz",
        "role":"user",
        "DirPath":"/Downloads/public"
    },]